name: pipeline de testes

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    steps:
      setup:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Install modules
            run: npm install
      cypress-tests-desktop:
        needs: setup
        runs-on: ubuntu-latest
        container: cypress/browsers:node12.18.3-chrome87-ff82
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Run tests on desktop viewport 🧪
            uses: cypress-io/github-action@v2

            with:
              command: npm test
      cypress-tests-tablet:
        needs: setup
        runs-on: ubuntu-latest
        container: cypress/browsers:node12.18.3-chrome87-ff82
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Run tests on tablet viewport 🧪
            uses: cypress-io/github-action@v2 

            with:
              command: npm run test:tablet